server:
  port: 8082
spring:
  datasource:
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
    password: ENC(AbU/3gDQLFUibkL0e1h/55PBH0PwA5VbKOw3B7z5hn1Ql/sPn8dpFjNzThWe3+Hl)
    url: jdbc:mysql://localhost:3306/MEcomm
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: ggpv ekzu dhvl gntz
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: fullstackwizard1526@gmail.com
